server:
  port: 8080
  servlet:
    contextPath: /api

spring:
  jpa:
    hibernate:
      ddl-auto: create

  datasource:
    url: jdbc:mysql://localhost:3306/db_userservice
    username: webservice
    password: welcome1

  security:
    user:
      name: myx
      password: 1qazxsw2
