server:
  port: 8080
  servlet:
    contextPath: /demo

spring:
  jpa:
    hibernate:
      ddl-auto: create
      
  datasource:
    url: jdbc:mysql://localhost:3306/db_demo
    username: demo
    password: welcome1
    

security:
  oauth2:
    resource:
      token-info-uri: http://localhost:8088/security/oauth/check_token
    client:
      client-id: clientID
      client-secret: clientSecret
       